### PR TITLE
Project settings

### PR DESCRIPTION
**Pull request by picman**
A solution for #42.

### CODE REVIEW

**Comment by maeda-m** [comment]
Please refer to #37 .

**Comment by picman** [comment]
I'm sorry but I don't understand your objections to my patch. the `super` is the problem? Why? If I'm overriding a method from a class, calling `super` is a standard way how use the original method. 
Of course, you can reject the patch but the plugins will remain in conflict then.

**Comment by maeda-m** [comment]
I agree that using `super` is the standard way to override `class` methods.

However, since `ProjectsHelper` is a `module`, I think it is incorrect to use `super`.

**Comment by ahorek** [comment]
@maeda-m I think there should be a `Module#prepend` instead of `ProjectsController.send :helper` ?

here'a an article about the difference
https://www.justinweiss.com/articles/rails-5-module-number-prepend-and-the-end-of-alias-method-chain/

**Comment by maeda-m** [comment]
Thank you. I learned from you.
Released [version 1.5.0](https://github.com/hidakatsuya/redmine_default_custom_query/releases/tag/1.5.0) !

**Pull request merged**
