### PR TITLE
Support Redmine 4.0

### PR DESCRIPTION
**Pull request by marius-balteanu**
Fixes: #38

Other changes:
- Drop unmaintained Redmine versions (3.2 and 3.1)
- Run tests against Ruby 2.5 and Ruby 2.6

### CODE REVIEW

**Comment by marius-balteanu** [comment]
I think it'll make our life simpler if we drop support for Redmine 3.3 and 3.4 and support only 4.0 in the new version.

@hidakatsuya, @maeda-m, do you agree?

**Comment by maeda-m** [comment]
Hello @marius-balteanu .
Thank you for a wonderful pull request.

I agree with your opinion. I thought it difficult to deal with "bundler" dependencies and "ActionDispatch::Integration#xhr" methods with various Rails versions.

**Comment by marius-balteanu** [comment]
Here it is the updated patch.

**Comment by maeda-m** [comment]
Merged. Thank you!

**Pull request merged**
